/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aggregator: typeof import('./src/components/home/Aggregator.vue')['default']
    AggregatorField: typeof import('./src/components/home/aggregator/AggregatorField.vue')['default']
    AppDeleteDialog: typeof import('./src/components/AppDeleteDialog.vue')['default']
    CreateInvitation: typeof import('./src/components/CreateInvitation.vue')['default']
    CreateInvitationBtn: typeof import('./src/components/CreateInvitationBtn.vue')['default']
    CreateInvitationCard: typeof import('./src/components/CreateInvitationCard.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    Hero: typeof import('./src/components/home/Hero.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ResendInvitationBtn: typeof import('./src/components/ResendInvitationBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDrawer: typeof import('./src/components/TheDrawer.vue')['default']
    UpdateInvitationEmail: typeof import('./src/components/UpdateInvitationEmail.vue')['default']
    Upload: typeof import('./src/components/home/Upload.vue')['default']
    Validator: typeof import('./src/components/home/Validator.vue')['default']
    ValidatorField: typeof import('./src/components/home/validator/ValidatorField.vue')['default']
    WelcomeDialog: typeof import('./src/components/home/WelcomeDialog.vue')['default']
  }
}
