"""add_schemas

Revision ID: 0004
Revises: 0003
Create Date: 2024-07-18 14:33:17.762426

"""

import sqlalchemy as sa
from alembic import op

from models import Category, Variable
from scripts.load_variables_and_categories import (
    get_categories_data,
    get_variables_data,
)

# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    variables_data = get_variables_data()
    categories_data = get_categories_data()
    op.bulk_insert(Variable.__table__, variables_data)
    op.bulk_insert(Category.__table__, categories_data)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.delete(Variable))
    op.execute(sa.delete(Category))
    # ### end Alembic commands ###
