"""add_aggregations

Revision ID: 0006
Revises: 0005
Create Date: 2024-09-09 06:37:05.416941

"""

import sqlalchemy as sa
from alembic import op

from models import Aggregation, AggregationSchema
from scripts.load_aggregations_and_aggregation_schemas import (
    get_aggregation_schemas_data,
    get_aggregations_data,
)

# revision identifiers, used by Alembic.
revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    aggregations_data = get_aggregations_data()
    aggregation_schemas_data = get_aggregation_schemas_data()
    op.bulk_insert(AggregationSchema.__table__, aggregation_schemas_data)
    op.bulk_insert(Aggregation.__table__, aggregations_data)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.delete(AggregationSchema))
    op.execute(sa.delete(Aggregation))
    # ### end Alembic commands ###
