"""add statistics table

Revision ID: ec58082b7947
Revises: 0004
Create Date: 2024-09-05 12:51:41.463143

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statistics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("aggregation_id", sa.String(), nullable=True),
        sa.Column("organisation_id", sa.String(), nullable=True),
        sa.Column("period_level", sa.String(), nullable=True),
        sa.Column("period", sa.Date(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.String(), nullable=True),
        sa.Column("grouping_category_1_value", sa.String(), nullable=True),
        sa.Column("grouping_category_2_value", sa.String(), nullable=True),
        sa.Column("grouping_variable_1_id", sa.String(), nullable=True),
        sa.Column("grouping_variable_2_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("statistics")
    # ### end Alembic commands ###
