version: "3.8"

services:
  fullstack:
    build:
      context: .
      dockerfile: ./fullstack-container/Dockerfile
    volumes:
      - ..:/workspace:cached
    depends_on:
      - db
    command: >
      bash -c "
      git config --global --add safe.directory /workspace
      && cd ./workspace/backend
      && poetry install --no-root
      && pre-commit install
      && cd ..
      && make alembic-upgrade
      && cd ./frontend
      && npm install --production=false
      && sleep infinity"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass # pragma: allowlist secret
      - POSTGRES_USER=caridata
      - POSTGRES_DB=caridata

  superset-server:
    image: superset
    build:
      context: ../superset
      dockerfile: ./Dockerfile
    restart: on-failure:3
    depends_on:
      - metadata-db
    environment:
      - SUPERSET_CONFIG_PATH=/app/docker/superset_config.py
    volumes:
      - ../superset/config:/app/docker
    ports:
      - "8088:8088"

  superset-init:
    image: superset
    restart: no
    command: ["/bin/init-superset.sh"]
    user: root
    depends_on:
      - metadata-db
    environment:
      - SUPERSET_CONFIG_PATH=/app/docker/superset_config.py
    volumes:
      - ../superset/config:/app/docker
    healthcheck:
      disable: true

  metadata-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=pass # pragma: allowlist secret
      - POSTGRES_USER=superset
      - POSTGRES_DB=superset
    volumes:
      - superset-metadata-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:
  superset-metadata-data:
